### ISSUE TITLE
Some Dlls are Not found

### ISSUE THREAD

**Issue by theyush** [naveenrajceg13/Automated-Ration-Shop-System-#1]
These dll should in my system.
I'm using windows 8.1 and these dlls are not found.

I searched on google also but din't find them anywhere
ATMServiceMessage
DPFPDevNet
DPFPSHerNet
DPFPGuiNet
DPFPVerNet

**Comment by naveenrajceg13** [comment]
http://www.fixerrorkit.com/fix-error/fix-DPFPDevNET.dll-error.html hope this link will help to fix your problem.

**Comment by theyush** [comment]
what about AtmMeassageService.dll ?

**Comment by naveenrajceg13** [comment]
All the mentioned .dll files should be present in the system.

**Comment by theyush** [comment]
no there are not present that's what I'm telling you.

**Comment by theyush** [comment]
can you provide me link for ATMMeassgeService dll file.

I found the others but this one is still missing
